model:
  name: 'afpb'
  pretrained: True

data:
  type: 'image'
  sources: ['cuhk03_labeled']
  targets: ['cuhk03_labeled']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip','random_erase','random_crop','random_patch']
  save_dir: 'log'
  exp_name: 'cuhk_labeled'

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4

loss:
  name: 'engine_AFPB'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.
    weight_x: 1.
  div_reg: True
  div_reg_start: 0 #50

train:
  optim: 'adam'
  lr: 0.000035
  max_epoch: 120
  batch_size: 128
  lr_scheduler: 'warmup'
  warmup_multiplier: 10
  warmup_total_epoch: 19
  stepsize: [40, 70]

cuhk03:
  labeled_images: True
  use_metric_cuhk03: False

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  start_eval: 60
  rerank: False
  visactmap: False
